import { execFile } from 'node:child_process'
import { createHash } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { promisify } from 'node:util'
import { afterEach, expect, test } from 'vitest'
import {
  parsePackageInfo,
  prepareAurPackage,
  renderInstallScript
} from '../scripts/prepare-aur-package.mjs'

const execFileAsync = promisify(execFile)
const temporaryDirectories: string[] = []

const packageInfo = `# Generated by fpm
#
pkgname = streamdeck-deej
pkgver = 4.2.0-1
pkgdesc =
 Desktop app for controlling StreamDeck buttons and DeeJ audio sliders via Arduino
url = https://github.com/lachaux-remi/StreamDeckDeeJ-App
arch = x86_64
license = MIT
depend = gtk3
depend = nss
depend = libappindicator-gtk3
`

const officialInstall = `post_install() {
    :
'/opt/streamdeck-deej/resources/linux/install-udev-rule' install
}
post_remove() {
    :
rm -f '/usr/bin/streamdeck-deej'
}
`

async function officialPackage(
  info = packageInfo,
  version = '4.2.0'
): Promise<{
  directory: string
  packagePath: string
  licensePath: string
}> {
  const directory = await mkdtemp(join(tmpdir(), 'aur-package-'))
  temporaryDirectories.push(directory)
  const root = join(directory, 'root')
  await execFileAsync('mkdir', ['-p', join(root, 'opt/streamdeck-deej')])
  await Promise.all([
    writeFile(join(root, '.PKGINFO'), info),
    writeFile(join(root, '.INSTALL'), officialInstall),
    writeFile(join(root, 'opt/streamdeck-deej/streamdeck-deej'), 'binary')
  ])
  const packagePath = join(directory, `streamdeck-deej-${version}.pkg.tar.xz`)
  await execFileAsync('tar', ['-cJf', packagePath, '-C', root, '.PKGINFO', '.INSTALL', 'opt'])
  const licensePath = join(directory, 'LICENSE')
  await writeFile(licensePath, 'MIT License\n')
  return { directory, packagePath, licensePath }
}

function sha256(bytes: Buffer): string {
  return createHash('sha256').update(bytes).digest('hex')
}

afterEach(async () => {
  await Promise.all(
    temporaryDirectories.splice(0).map((directory) => rm(directory, { recursive: true }))
  )
})

test('parses fpm package metadata including wrapped values', () => {
  expect(parsePackageInfo(packageInfo)).toMatchObject({
    pkgname: 'streamdeck-deej',
    pkgver: '4.2.0-1',
    pkgdesc: 'Desktop app for controlling StreamDeck buttons and DeeJ audio sliders via Arduino',
    depends: ['gtk3', 'nss', 'libappindicator-gtk3']
  })
})

test('generates a -bin PKGBUILD pinned to the official release package', async () => {
  const { directory, packagePath, licensePath } = await officialPackage()
  const output = join(directory, 'aur')
  await prepareAurPackage(packagePath, '4.2.0', licensePath, output)

  const pkgbuild = await readFile(join(output, 'PKGBUILD'), 'utf8')
  expect(pkgbuild).toContain('pkgname=streamdeck-deej-bin\n')
  expect(pkgbuild).toContain('pkgver=4.2.0\n')
  expect(pkgbuild).toContain(
    "pkgdesc='Desktop app for controlling StreamDeck buttons and DeeJ audio sliders via Arduino'"
  )
  expect(pkgbuild).toContain("depends=('gtk3' 'nss' 'libappindicator-gtk3')")
  expect(pkgbuild).toContain('provides=("$_pkgname=$pkgver")')
  expect(pkgbuild).toContain('conflicts=("$_pkgname")')
  expect(pkgbuild).toContain('$url/releases/download/v$pkgver/$_pkgname-$pkgver.pkg.tar.xz')
  expect(pkgbuild).toContain(
    `sha256sums=('${sha256(await readFile(packagePath))}'\n            '${sha256(await readFile(licensePath))}')`
  )
  expect(pkgbuild).toContain('--exclude .PKGINFO --exclude .MTREE --exclude .INSTALL')
  expect(pkgbuild).toContain('"$pkgdir/usr/share/licenses/$pkgname/LICENSE"')

  const install = await readFile(join(output, 'streamdeck-deej-bin.install'), 'utf8')
  expect(install.startsWith(officialInstall.trimEnd())).toBe(true)
  expect(install).toContain('post_upgrade() {\n  post_install\n}\n')
})

test('refuses packages that do not match the requested release', async () => {
  const { directory, packagePath, licensePath } = await officialPackage()
  await expect(
    prepareAurPackage(packagePath, '4.2.1', licensePath, join(directory, 'aur'))
  ).rejects.toThrow()

  const other = await officialPackage(packageInfo.replace('4.2.0-1', '4.1.0-1'))
  await expect(
    prepareAurPackage(other.packagePath, '4.2.0', other.licensePath, join(other.directory, 'aur'))
  ).rejects.toThrow()
})

test('refuses metadata that would inject shell code into the PKGBUILD', async () => {
  const injected = await officialPackage(packageInfo.replace('depend = nss', 'depend = nss$(id)'))
  await expect(
    prepareAurPackage(
      injected.packagePath,
      '4.2.0',
      injected.licensePath,
      join(injected.directory, 'aur')
    )
  ).rejects.toThrow(/Unsafe PKGBUILD value/)

  const quoted = await officialPackage(packageInfo.replace('via Arduino', "via Arduino'"))
  await expect(
    prepareAurPackage(
      quoted.packagePath,
      '4.2.0',
      quoted.licensePath,
      join(quoted.directory, 'aur')
    )
  ).rejects.toThrow(/Unsafe PKGBUILD string/)
})

test('requires the official install and removal scriptlets', () => {
  expect(() => renderInstallScript('post_remove() {\n:\n}\n')).toThrow(/post_install/)
  expect(() => renderInstallScript('post_install() {\n:\n}\n')).toThrow(/post_remove/)
})

test('publishes to the AUR only after verifying and building the signed release', () => {
  const workflow = readFileSync('.github/workflows/aur.yml', 'utf8')
  const prepare = workflow.slice(workflow.indexOf('  prepare:'), workflow.indexOf('  build:'))
  const build = workflow.slice(workflow.indexOf('  build:'), workflow.indexOf('  publish:'))
  const publish = workflow.slice(workflow.indexOf('  publish:'))

  expect(prepare).toContain('node scripts/update-signing.mjs verify release-artifacts')
  expect(prepare).toContain('node scripts/prepare-aur-package.mjs')
  expect(build).toMatch(/container: archlinux:base-devel@sha256:[0-9a-f]{64}/)
  expect(build).toContain('makepkg --printsrcinfo > .SRCINFO && makepkg --nodeps --noconfirm')
  expect(`${prepare}${build}`).not.toContain('secrets.')
  expect(publish).toContain('needs: build')
  expect(publish).toContain('environment: aur')
  expect(publish).toContain('AUR_SSH_PRIVATE_KEY: ${{ secrets.AUR_SSH_PRIVATE_KEY }}')
  expect(publish).toContain('StrictHostKeyChecking=yes')
  expect(publish).toContain(
    'aur.archlinux.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEuBKrPzbawxA/k2g6NcyV5jmqwJ2s+zpgZGZ7tpLIcN'
  )
  expect(publish).toContain('git push origin HEAD:master')
})

test('the release workflow publishes to the AUR after the GitHub release', () => {
  const workflow = readFileSync('.github/workflows/release.yml', 'utf8')
  const job = workflow.slice(workflow.indexOf('  publish-aur:'))

  expect(job).toContain('needs: [create-release, publish-release]')
  expect(job).toContain("if: ${{ needs.create-release.outputs.release_created == 'true' }}")
  expect(job).toContain('uses: ./.github/workflows/aur.yml')
  expect(job).toContain('tag: ${{ needs.create-release.outputs.tag_name }}')
})

test('keeps the official post_upgrade when the release package already has one', () => {
  const withUpgrade = `${officialInstall}post_upgrade() {\n    :\n'/opt/streamdeck-deej/resources/linux/install-udev-rule' install\n}\n`
  expect(renderInstallScript(withUpgrade)).toBe(withUpgrade)
  expect(renderInstallScript(withUpgrade).match(/^post_upgrade\(\)/gm)).toHaveLength(1)
})
