#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=13

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
ENV_FILE="${ENV_FILE_OVERRIDE:-$SCRIPT_DIR/validation.env}"

banner "StreamDeckDeeJ Windows 11 VM and hardware validation"

stage "Host and validation identity"
say "Capture the non-secret identity of the Linux host and validation run."
ask HOST_DISTRIBUTION "Linux distribution and version (for example Fedora 42):"
ask LIBVIRT_URI "libvirt URI [qemu:///system]:"
LIBVIRT_URI="${LIBVIRT_URI:-qemu:///system}"
ask VM_NAME "VM name [streamdeck-deej-win11]:"
VM_NAME="${VM_NAME:-streamdeck-deej-win11}"
ask VALIDATION_RUN_ID "Validation run ID (for example windows-4.2.0-rc1):"
write_env HOST_DISTRIBUTION "$HOST_DISTRIBUTION"
write_env LIBVIRT_URI "$LIBVIRT_URI"
write_env VM_NAME "$VM_NAME"
write_env VALIDATION_RUN_ID "$VALIDATION_RUN_ID"
step "Run: LIBVIRT_URI='$LIBVIRT_URI' VM_NAME='$VM_NAME' '$SCRIPT_DIR/host/preflight.sh'"
warn "The preflight is read-only and is expected to fail until the VM and USB device exist."
pause "Run or review the preflight, then press Enter."

stage "Windows installation media"
open_url "https://www.microsoft.com/software-download/windows11"
step "Download an official Windows 11 x64 ISO. Do not paste a product key into this wizard."
ask WINDOWS_ISO "Absolute path to the Windows 11 x64 ISO:"
ask WINDOWS_EDITION "Windows edition [Windows 11 Pro]:"
WINDOWS_EDITION="${WINDOWS_EDITION:-Windows 11 Pro}"
write_env WINDOWS_ISO "$WINDOWS_ISO"
write_env WINDOWS_EDITION "$WINDOWS_EDITION"

stage "Create the QEMU/KVM virtual machine"
step "In virt-manager, create '$VM_NAME' from '$WINDOWS_ISO' and select Windows 11."
step "Before install: Q35, UEFI Secure Boot, vTPM 2.0 emulator, host-passthrough CPU."
step "Assign 4 vCPU, 8192 MiB RAM, 80 GiB qcow2, xHCI USB, NAT network and virtual audio."
step "Install Windows with a dedicated local validation account and complete Windows Update."
pause "Confirm Windows 11 reaches the desktop."

stage "Verify UEFI, TPM and guest prerequisites"
step "Open elevated PowerShell in Windows."
step "Run: Get-Tpm | Format-List TpmPresent,TpmReady,ManagedAuthLevel"
step "Run: Confirm-SecureBootUEFI"
step "Run: (Get-CimInstance Win32_OperatingSystem).OSArchitecture"
step "Require TpmPresent=True, TpmReady=True, Secure Boot=True and 64-bit."
step "Shut down the VM and create the complete win11-clean restoration point before adding tools."
pause "Confirm all checks passed and win11-clean exists."

stage "Install the Windows development toolchain"
open_url "https://learn.microsoft.com/visualstudio/install/workload-and-component-ids?view=vs-2022"
step "Copy guest/*.ps1 into C:\\Validation\\guest in the VM."
ask VS_EDITION "Visual Studio edition, Community or BuildTools [Community]:"
VS_EDITION="${VS_EDITION:-Community}"
write_env VS_EDITION "$VS_EDITION"
step "From elevated PowerShell run: Set-ExecutionPolicy -Scope Process Bypass"
step "Run: C:\\Validation\\guest\\Bootstrap-WindowsValidation.ps1 -VisualStudioEdition $VS_EDITION"
step "Reboot after the script verifies Visual Studio C++, Windows SDK, Node 24 and pnpm 11.22.0."
pause "Confirm the bootstrap and reboot completed."

stage "Create complete restoration points"
warn "A disk-only snapshot can omit UEFI NVRAM or swtpm state. Stop the VM first."
step "Create win11-toolchain now, preserving qcow2, domain XML, NVRAM and swtpm state together."
step "If libvirt rejects a vTPM snapshot, clone the stopped VM instead; do not disable TPM."
pause "Confirm win11-toolchain can be restored as one unit."

stage "Attach the complete composite USB device"
step "On Linux confirm: lsusb -d 5239:0001"
step "In virt-manager: Add Hardware → USB Host Device → choose 5239:0001."
step "Alternative XML is $SCRIPT_DIR/host/streamdeck-deej-usb.xml."
step "Inside Windows confirm one USB composite parent, one COM interface and the expected HID interface."
ask WINDOWS_COM_PORT "Assigned Windows COM port (for example COM7):"
write_env WINDOWS_COM_PORT "$WINDOWS_COM_PORT"
pause "Confirm the whole device, not individual interfaces, is attached."

stage "Select N−1 and N artifacts"
warn "No Windows N−1 is published yet. Use two genuine consecutive stable Windows releases or mark BLOCKED."
ask N_MINUS_ONE_VERSION "N−1 Windows version, or BLOCKED if none exists:"
ask N_MINUS_ONE_INSTALLER "Absolute path to the N−1 NSIS installer, or BLOCKED:"
ask N_VERSION "N Windows version:"
ask N_INSTALLER "Absolute path to the N NSIS installer:"
ask N_RELEASE_ASSETS_DIRECTORY "Directory containing N setup, blockmap, latest.yml, manifest and signature:"
write_env N_MINUS_ONE_VERSION "$N_MINUS_ONE_VERSION"
write_env N_MINUS_ONE_INSTALLER "$N_MINUS_ONE_INSTALLER"
write_env N_VERSION "$N_VERSION"
write_env N_INSTALLER "$N_INSTALLER"
write_env N_RELEASE_ASSETS_DIRECTORY "$N_RELEASE_ASSETS_DIRECTORY"
step "In non-elevated PowerShell run: & C:\\Validation\\guest\\Collect-WindowsEvidence.ps1 -Phase before-install -NMinusOneInstaller '$N_MINUS_ONE_INSTALLER' -NInstaller '$N_INSTALLER' -NReleaseAssetsDirectory '$N_RELEASE_ASSETS_DIRECTORY'"
step "Require five exact N assets. Authenticode status NotSigned is expected; Ed25519 protects updater assets."
pause "Confirm hashes and the five-asset inventory were recorded, or updater is marked BLOCKED."

stage "Install N−1 and validate desktop lifecycle"
step "Restore win11-toolchain, then install N−1 from Explorer without elevation."
step "After checking official GitHub origin and SHA-512, accept SmartScreen via More info → Run anyway."
step "Confirm no UAC; installation is per-user and allows directory selection. Authenticode is out of roadmap."
step "Exercise close-to-tray, tray restore, minimized second-instance restore and focus."
step "Exercise runInBackground, tray Quit, and exactly one durable application process."
step "Collect after-install-n-minus-one evidence and create snapshot streamdeck-n-minus-one."
pause "Record PASS/FAIL and observations in the generated notes.txt."

stage "Autostart, logoff, reboot and N−1→N updater"
step "Enable runOnStartup; collect evidence; log off/on and verify one background instance."
step "Reboot and verify again; disable runOnStartup, reboot and verify no automatic launch."
step "Restore streamdeck-n-minus-one; Check must offer stable N without downloading automatically."
step "Download manually, observe 0–100%, then Install; accept SmartScreen if shown and require version N."
step "The official success path must use signed manifest, signature, latest.yml, exact setup and blockmap together."
step "Repeat from tray/background; test reboot after download but before requesting install."
warn "Never force shutdown/logoff while NSIS is writing files; electron-updater 6.x is not atomic there."
step "Collect after-update-n evidence and require the running version to be N."
pause "Record lifecycle and updater verdicts."

stage "Core Audio sessions"
step "Play sound concurrently in Edge and Windows Media Player on the default multimedia endpoint."
step "Verify master plus lower-case process names, with isolated sliders at 0/50/100%."
step "Open two processes with the same executable name; both must follow the same assignment."
step "Leave a slider at 30%, restart its app, and require reapplication within five seconds."
step "Switch the default output endpoint, relaunch playback and retest master plus one app session."
step "A native endpoint failure may log an error but must not terminate the application."
ask AUDIO_APPLICATIONS "Audio applications used [Edge,Windows Media Player]:"
AUDIO_APPLICATIONS="${AUDIO_APPLICATIONS:-Edge,Windows Media Player}"
write_env AUDIO_APPLICATIONS "$AUDIO_APPLICATIONS"
pause "Record audible and sndvol.exe observations."

stage "Serial protocol, HID and LEDs"
step "Close StreamDeckDeeJ-App so the serial harness can own $WINDOWS_COM_PORT exclusively."
step "Run: C:\\Validation\\guest\\Test-SerialProtocol.ps1 -Port $WINDOWS_COM_PORT -DurationSeconds 30"
step "Move sliders and generate pressed/hold/released events; require valid JSON and no invalid frames."
step "Launch the app, select $WINDOWS_COM_PORT, then unplug/replug and verify reconnect without relaunch."
step "Test HID interface=2 usage=1, 16 LEDs, static/rainbow, brightness 0/50/100 and shutdown black."
step "After HID unplug, wait at least 5 seconds, replug and require animation recovery."
pause "Record serial, reconnect and visual LED verdicts."

stage "Sleep, uninstall and archive evidence"
step "If guest S3 exists, sleep/resume once attached and once unplugged during sleep."
step "If S3 is absent, record GUEST_SLEEP_UNAVAILABLE; libvirt suspend/resume is a distinct fallback."
step "Quit, disable autostart, uninstall without elevation, reboot and require no automatic process."
step "Confirm executables/shortcuts are gone but user data remains; reinstall N and verify config reuse."
step "Collect after-uninstall and after-reinstall evidence. Archive evidence with artifact SHA-512."
step "Use only PASS, FAIL, BLOCKED or NOT_APPLICABLE; any BLOCKED prevents a global PASS."
pause "Confirm the report and evidence archive are complete."

finish
